# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - u10app(debug)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://f4repo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_79e59a575b9e4533b0c541c0bdb21c7e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5980307479ea46c3b3e35fe586dae4af }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: f4repo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79e59a575b9e4533b0c541c0bdb21c7e }}/f4repo/azuredocs/go:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'debug'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'u10app'
        slot-name: 'debug'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f8dc35bfde54a3cb1c4149468f16c58 }}
        images: 'f4repo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79e59a575b9e4533b0c541c0bdb21c7e }}/f4repo/azuredocs/go:${{ github.sha }}'